# Generated by Django 6.1.1 on 2026-09-11 10:08

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('body', models.TextField(blank=True)),
                ('push_preview', models.CharField(blank=True, max_length=120)),
                ('audience_classification', models.CharField(blank=True, choices=[('journeyman', 'Journeyman'), ('apprentice', 'Apprentice'), ('foreman', 'Foreman'), ('retiree', 'Retiree')], max_length=20)),
                ('needs_ack', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('approved', 'Approved'), ('sending', 'Sending'), ('sent', 'Sent'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client_idempotency_key', models.CharField(blank=True, max_length=255)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='announcements_approved', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='announcements_created', to=settings.AUTH_USER_MODEL)),
                ('local', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to='core.local')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('pending', 'Pending'), ('delivered', 'Delivered'), ('read', 'Read'), ('acknowledged', 'Acknowledged'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('rsvp', models.CharField(blank=True, choices=[('coming', 'Coming'), ('cannot_attend', 'Cannot attend')], max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('announcement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='callouts.announcement')),
                ('local', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='core.local')),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('delivered', 'Delivered'), ('read', 'Read'), ('acknowledged', 'Acknowledged'), ('rsvp_recorded', 'RSVP recorded'), ('failed', 'Failed')], max_length=20)),
                ('occurred_at', models.DateTimeField(auto_now_add=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('actor_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_events', to=settings.AUTH_USER_MODEL)),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='callouts.delivery')),
            ],
            options={
                'ordering': ['occurred_at'],
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('classification', models.CharField(choices=[('journeyman', 'Journeyman'), ('apprentice', 'Apprentice'), ('foreman', 'Foreman'), ('retiree', 'Retiree')], max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('retired', 'Retired'), ('suspended', 'Suspended')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('local', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='core.local')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='member_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='delivery',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='callouts.member'),
        ),
        migrations.CreateModel(
            name='NotificationAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(default='log', max_length=50)),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('failed', 'Failed')], max_length=20)),
                ('attempted_at', models.DateTimeField(auto_now_add=True)),
                ('provider_message_id', models.CharField(blank=True, max_length=255, null=True)),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_attempts', to='callouts.delivery')),
            ],
            options={
                'ordering': ['attempted_at'],
            },
        ),
        migrations.CreateModel(
            name='OutboxEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('announcement.send', 'Announcement send')], max_length=50)),
                ('aggregate_id', models.CharField(max_length=255)),
                ('payload', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['published_at'], name='callouts_ou_publish_f83ffa_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='announcement',
            index=models.Index(fields=['local', 'status'], name='callouts_an_local_i_1960d6_idx'),
        ),
        migrations.AddConstraint(
            model_name='announcement',
            constraint=models.UniqueConstraint(condition=models.Q(('client_idempotency_key', ''), _negated=True), fields=('local', 'client_idempotency_key'), name='unique_local_idempotency_key'),
        ),
        migrations.AddIndex(
            model_name='deliveryevent',
            index=models.Index(fields=['delivery', 'type'], name='callouts_de_deliver_966a99_idx'),
        ),
        migrations.AddIndex(
            model_name='member',
            index=models.Index(fields=['local', 'status'], name='callouts_me_local_i_2cc20a_idx'),
        ),
        migrations.AddIndex(
            model_name='member',
            index=models.Index(fields=['local', 'classification'], name='callouts_me_local_i_88d834_idx'),
        ),
        migrations.AddIndex(
            model_name='delivery',
            index=models.Index(fields=['announcement', 'state'], name='callouts_de_announc_3ca23a_idx'),
        ),
        migrations.AddIndex(
            model_name='delivery',
            index=models.Index(fields=['member', 'state'], name='callouts_de_member__b611cc_idx'),
        ),
        migrations.AddConstraint(
            model_name='delivery',
            constraint=models.UniqueConstraint(fields=('announcement', 'member'), name='unique_delivery_per_announcement_member'),
        ),
        migrations.AddIndex(
            model_name='notificationattempt',
            index=models.Index(fields=['delivery', 'attempted_at'], name='callouts_no_deliver_5a3b91_idx'),
        ),
    ]
